### ISSUE TITLE
QDeferred in method argument

### ISSUE THREAD

**Issue by devgvlad** [juangburgos/QDeferred#1] opened 2020-10-28 10:20 UTC
I have the following code:
`class MyClient : public QObject
{
    Q_OBJECT
public:
    explicit MyClient(QObject *parent = nullptr);
    QDeferred<int> connect(const QString &strAddress);
private:
    void process(QDeferred<int> retdef);

private:
    QDeferred<int> def;
};`

And

`MyClient::MyClient(QObject *parent) : QObject(parent)
{

}

QDeferred<int> MyClient::connect(const QString &strAddress)
{
    QDeferred<int> retDefered;
    process(retDefered);
    return retDefered;
}

void MyClient::process(QDeferred<int> retdef)
{
    def = retDefered;
    // Some work. Return type process must be void.
    def.resolve(10);
}
`

So. It`s work, but crash when application is finished.
**QDeferredDataBase was deleted.
12:19:30: The program has unexpectedly finished.**

**Comment by juangburgos** [comment] 2020-10-28 11:07
Your example is not correct. `QDeferred<T>` cannot be defined without a template argument `T` So it would not compile. If it is a deferred object without argument then you use `QDefer` instead. 

Looking at the `MyClient::process` I could infer you want a `QDeferred<int>`, because you resolve it with a `10` value?

Also this method would not compile because you pass `retdef` as argument and not use it, then use `retDefered` which is not defined.

**Do you have any other working code snippet that reproduces the issue?**

The following code compiles, runs and closes correctly:

`mian.cpp`

```c++
#include <QCoreApplication>
#include <QDebug>

#include "myclient.h"

int main(int argc, char *argv[])
{
    QCoreApplication a(argc, argv);

    MyClient client;

    client.connect("127.0.0.1")
    .done([](int num) {
        qDebug() << "Success, num=" << num;
    })
    .fail([](int num) {
        Q_UNUSED(num);
        qDebug() << "Something went wrong";
    });

    return a.exec();
}
```

`myclient.h`

```c++
#ifndef MYCLIENT_H
#define MYCLIENT_H

#include <QObject>
#include <QDeferred>

class MyClient : public QObject
{
    Q_OBJECT
public:
    explicit MyClient(QObject *parent = nullptr);

    QDeferred<int> connect(const QString &strAddress);

private:

    void process(QDeferred<int> retdef);

    QDeferred<int> def;

};

#endif // MYCLIENT_H
```

`myclient.cpp`

```c++
#include "myclient.h"

MyClient::MyClient(QObject *parent) : QObject(parent)
{

}

QDeferred<int> MyClient::connect(const QString& strAddress)
{
    QDeferred<int> retDefered;
    process(retDefered);
    return retDefered;
}

void MyClient::process(QDeferred<int> retdef)
{
    def = retdef;
    // Some work. Return type process must be void.
    def.resolve(10);
}
```

**Comment by devgvlad** [comment] 2020-10-29 09:13
I created an empty quick application and used your class MyClient above - fully copied your example. 
When the application is closed, console output:
**Success, num= 10
QDeferredDataBase was deleted.
10:53:33: /home/vi/Templates/build-untitled-Desktop_Qt_5_15_1_GCC_64bit-Release/untitled exited with code 0**

Ok. I copied the MyClient class into my project and here's a when I closed the application:
**QDeferredDataBase was deleted.
11:00:38: The program has unexpectedly finished.
11:00:38: The process was ended forcefully.
11:00:39: /home/vi/Work/SDRLABS/MagicSDR-Mobile/build-MagicSDR-Desktop_Qt_5_15_1_GCC_64bit-Release/MagicSDR crashed.**

OS: ubuntu 20.04

**Comment by devgvlad** [comment] 2020-10-29 09:16
I created an empty quick application and used your class MyClient above - fully copied your example.
When the application is closed, console output:
Success, num= 10
QDeferredDataBase was deleted.
10:53:33: /home/vi/Templates/build-untitled-Desktop_Qt_5_15_1_GCC_64bit-Release/untitled exited with code 0

Ok. I copied the MyClient class into my project and here's a when I closed the application:
QDeferredDataBase was deleted.
11:00:38: The program has unexpectedly finished.
11:00:38: The process was ended forcefully.
11:00:39: /home/vi/Work/SDRLABS/MagicSDR-Mobile/build-MagicSDR-Desktop_Qt_5_15_1_GCC_64bit-Release/application crashed.

OS: ubuntu 20.04

**Comment by devgvlad** [comment] 2020-10-29 09:19
I created an empty quick application and used your class MyClient above - fully copied your example.
When the application is closed, console output:
**Success, num= 10
QDeferredDataBase was deleted.
10:53:33: /home/vi/Templates/build-untitled-Desktop_Qt_5_15_1_GCC_64bit-Release/untitled exited with code 0**

Ok. I copied the MyClient class into my project and here's a when I closed the application:
**QDeferredDataBase was deleted.
11:00:38: The program has unexpectedly finished.
11:00:38: The process was ended forcefully.
11:00:39: /home/vi/Work/SDRLABS/Application/build-Application-Desktop_Qt_5_15_1_GCC_64bit-Release/Application/crashed.**

OS: ubuntu 20.04

**Comment by devgvlad** [comment] 2020-10-29 09:19
I created an empty quick application and used your class MyClient above - fully copied your example.
When the application is closed, console output:
**Success, num= 10
QDeferredDataBase was deleted.
10:53:33: /home/vi/Templates/build-untitled-Desktop_Qt_5_15_1_GCC_64bit-Release/untitled exited with code 0**

Ok. I copied the MyClient class into my project and here's a when I closed the application:
**QDeferredDataBase was deleted.
11:00:38: The program has unexpectedly finished.
11:00:38: The process was ended forcefully.
11:00:39: /home/vi/Work/Application/build-Application-Desktop_Qt_5_15_1_GCC_64bit-Release/Application/crashed.**

OS: ubuntu 20.04

**Comment by juangburgos** [comment] 2020-10-29 09:48
So the issue is not in the `MyClient` class but elsewhere in your application. Are you suing some IDE where you can debug? Maybe look at the call stack where the debugger stops when the crash occurs?

**Comment by devgvlad** [comment] 2020-10-30 11:36
Thanks! I have successfully integrated your library into my project.

**Comment by juangburgos** [comment] 2020-10-30 11:52
Happy to help, closing issue.

**Closed by juangburgos** 2020-10-30 11:52 UTC
